# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: rainbow_database
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432
    networks:
      - ruqqus
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    networks:
      - ruqqus
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fakedomain.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - ruqqus
    restart: unless-stopped
  ruqqus:
    build: ./
    ports:
      - 8000:8000
    environment:
      MASTER_KEY: changeme
      DATABASE_URL: postgresql://unicorn_user:magical_password@database/ruqqus
      domain: dev.localhost:8000
      REDIS_URL: redis://redis:6379
      IS_DEV: 1
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      - redis
    networks:
      - ruqqus
networks:
  ruqqus:
    driver: bridge
volumes:
  pgadmin: #
  database-data: # named volumes can be managed easier using docker-compose
